version: '3.8'

services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=datahargaproperti
      - MYSQL_USER=untuktst
      - MYSQL_PASSWORD=tst2022
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database:/docker-entrypoint-initdb.d/

  api:
    build: .
    environment:
      - IS_DEPLOYED=yes
    links:
      - mysqldb
    ports:
      - 80:5000
    depends_on:
      - mysqldb




