version: '3.8'

services:
  api:
    build: .
    links:
      - db
    ports:
      - 5000:5000
  
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

